apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.application.name }}-3-inbound
  namespace: {{ .Values.application.name }}-1
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.application.name }}-3
    ports:
    - protocol: TCP
      port: 80
