apiVersion: {{ .Values.application.name }}s/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}-1
  namespace: {{ .Values.application.name }}-1
  labels:
    {{ .Values.application.name }}: {{ .Values.application.name }}-1
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ .Values.application.name }}: {{ .Values.application.name }}-1
  template:
    metadata:
      labels:
        {{ .Values.application.name }}: {{ .Values.application.name }}-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-1
  namespace: {{ .Values.application.name }}-1
spec:
  selector:
    {{ .Values.application.name }}: {{ .Values.application.name }}-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80